### ISSUE TITLE
Missing wlan interface on Raspberry pi 3

### ISSUE THREAD

**Issue by Jimmy89** [DieterReuter/image-builder-rpi64#2]
I wanted to use a special docker pi in a remote place. Therefore I tried to enable the Wifi interface.

It turns out that the interface does not exists (when I used the command `ifconfig -a`).
Also the details entered with the img Hypriot flashing tool do not work.

How can I enable the Wifi?

**Comment by DieterReuter** [comment]
I just included the support for internal RPi3 WiFi module in the latest release, see https://github.com/DieterReuter/image-builder-rpi64/releases/tag/v20171007-083124. Can be easily configured by device init config file `/boot/device-init.yaml`.
