### ISSUE TITLE
Update cmdline.txt for memory cgroup

### ISSUE THREAD

**Issue by ecliptik** [DieterReuter/image-builder-rpi64#40]
v20171130-113423 sets `/boot/cmdline.txt` with `cgroup_enable=memory`, which does not setup the memory cgroup properly and causes kubeadm to fail pre-flight checks.

<img width="1419" alt="screen shot 2017-11-30 at 10 32 10 pm" src="https://user-images.githubusercontent.com/1261742/33470943-d1b02a1a-d61f-11e7-85d4-b0a0a6c4ecd7.png">

<img width="1318" alt="screen shot 2017-11-30 at 10 32 31 pm" src="https://user-images.githubusercontent.com/1261742/33470958-d7bb6d7a-d61f-11e7-928e-3529f6d799bf.png">

This has changed in recent kernels according to https://archlinuxarm.org/forum/viewtopic.php?f=15&t=12086#p57035.

To fix this, `/boot/cmdline.txt`should use `cgroup_memory=1` instead.

Updated this on a v20171130-113423 Raspberry Pi and rebooted, and kubeadm passes pre-flight checks and setups up k8s properly.

**Comment by StefanScherer** [comment]
So both `cgroup_enable=cpuset cgroup_enable=memory` should be replaced by `cgroup_memory=1` ?

**Comment by ecliptik** [comment]
@StefanScherer I think `cgroup_enable=cpuset` can stay, I didn't update it on my rpi nodes, just replaced `cgroup_enable=memory` with `cgroup_memory=1` and kubeadm pre-flight checks all passed after that.

**Comment by StefanScherer** [comment]
@ecliptik Yes thanks. Just after typing my question I found it myself after looking closer to the keywords :-)
I think @DieterReuter will merge your PR asap and publish a fixed release. Thank you!
