### ISSUE TITLE
Missing dirmngr package causes adding GPG keys for apt with cloud-init to fail

### ISSUE THREAD

**Issue by ecliptik** [DieterReuter/image-builder-rpi64#56]
Using the latest [v20180107-184643](https://github.com/DieterReuter/image-builder-rpi64/releases/tag/v20180107-184643) image on an RPI3, `cloud-init` fails to add GPG keys for apt repositories example due to missing the package `dirmngr`. Error in `/var/log/cloud-init-out.log` with example [user-data.yml](https://github.com/ecliptik/rpi/blob/master/hypriot/user-data.yml),

```
Command: ['gpg', '--keyserver', 'keyserver.ubuntu.com', '--recv', 'A7317B0F']
Exit code: 2
Reason: -
Stdout: -
Stderr: gpg: failed to start the dirmngr '/usr/bin/dirmngr': No such file or directory
        gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
        gpg: keyserver receive failed: No dirmngr

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/gpg.py", line 54, in getkeybyid
    recv_key(keyid, keyserver=keyserver)
  File "/usr/lib/python3/dist-packages/cloudinit/gpg.py", line 37, in recv_key
    (key, keyserver, error))
ValueError: Failed to import key "A7317B0F" from server "keyserver.ubuntu.com" - error Unexpected error while running command.
```

After adding `dirmngr` manually, `gpg` commands works properly. The image also seems to be missing the `less` package.

The previous release [v20171221-092341](https://github.com/DieterReuter/image-builder-rpi64/releases/tag/v20171221-092341) works properly using the same `user-data.yml` and includes the `dirmngr` package.

Looking over commit history, it seems that the image was updated to user a newer version of [os-rootfs](https://github.com/hypriot/os-rootfs). The tarballs of [v1.2.4](https://github.com/hypriot/os-rootfs/releases/tag/v1.2.4) and [v1.2.5](https://github.com/hypriot/os-rootfs/releases/tag/v1.2.5) both do not include the `dirmngr` or `less` commands. I will open an issue in this repository as well.

**Comment by DieterReuter** [comment]
Thanks for your input. As these packages are dependencies on `cloud-init` I think it's better to install them together. So PR #57 resolves this issue.
