### ISSUE TITLE
What is the appropriate method of updating the iptables rules?

### ISSUE THREAD

**Issue by troyfontaine** [DieterReuter/image-builder-rpi64#58]
I'm attempting to use Hypriot for a non-docker related task and can't seem to pin down the appropriate method of updating the iptables rules (or even getting them to reload from a file after they seemed to refresh themselves).  Can you point me to a method of tweaking them?

**Comment by DieterReuter** [comment]
This is a standard Debian:8 (Stretch) OS, so nothing special here. I just packaged it together with all the Docker tools. So the handling of iptables should be standard, expect that Docker is defining it's own iptables rules. But if you don't need Docker you could easily uninstall it or you fork this repo and create your customised OS image w/o Docker tools.
Does this explanation helps?

**Comment by troyfontaine** [comment]
Thanks!  I’ll try and tweak my own build to see if I have better luck!
