### ISSUE TITLE
Can iptable be installed?

### ISSUE THREAD

**Issue by robinsonlucas** [DieterReuter/image-builder-rpi64#78]
I'm using hypriot to implement some database but I need to configure the ports to access it. Sadly its look like iptable isnt available in the native version, and send back some 'E: unable to locate package iptable' when trying to install it. I tried all the apt-get update, upgrade and install thing but it doesn't work. So I'm wondering if iptable can be installed on hypriotos anyway? (and how if that so).
Thanks!

**Comment by ttyS0** [comment]
You need to add an `s`. 

`apt install iptables` will get you there.

**Comment by robinsonlucas** [comment]
Thanks. It works. Now I feel really dumb.

**Comment by ttyS0** [comment]
We've all been there. 😄
