### ISSUE TITLE
passwd

### ISSUE THREAD

**Issue by fachos** [DieterReuter/image-builder-rpi64#92]
hi.. i have change the passwd... but after boot again still using hyproit... where i can change? tq

**Comment by neta540** [comment]
The password is set by cloud-init on startup at the file located at  /boot/user-data

https://github.com/DieterReuter/image-builder-rpi64/blob/b9b4381a11103434b78c5c4cf478d9a2deb04e03/builder/files/boot/user-data#L21

**Comment by fachos** [comment]
ok thank you...
